version: '3'

services:
  smtp:
    image: bytemark/smtp
    env_file:
      - .env
    restart: always
    environment:
      RELAY_HOST: smtp.selxpress.com
      RELAY_PORT: 587
      RELAY_USERNAME: support@selxpress.com
      RELAY_PASSWORD: ${RELAY_PASSWORD}

  mssql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports: 
      - "1433:1433" 
    restart: always
    environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    networks:
      - network

  api:
    build: 
      context: ../SelXPressApi/SelXPressApi
    env_file:
      - .env
    ports:
      - 5288:80
      - 7094:443
    restart: on-failure
    networks:
      - network
    depends_on:
      - mssql
      - smtp

  front:
    build: ../sell_x_press_front_office
    env_file:
      - .env
    ports:
      - 4000:8080
    restart: on-failure
    networks:
      - network
    depends_on:
      - api

  back_office:
    build: ../sell_x_press_back_office
    env_file:
      - .env
    ports:
      - 4001:8080
    restart: on-failure
    networks:
      - network
    depends_on:
      - api 

volumes:
  db-data:
    driver: local

networks:
  network:
